# Generated by Django 4.0.6 on 2022-08-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.URLField(default='https://miro.medium.com/max/720/1*W35QUSvGpcLuxPo3SRTH4w.png'),
        ),
    ]
