version: '3'

services:
  #PostgresDB
  pgsql:
    image: postgres:14
    container_name: pgsql
    # volumes: # Todo:// Add your volumes
    #   - /my/own/datadir:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB : cv_creation
      POSTGRES_PASSWORD: Welcome411
    ports:
      - "5432:5432"


  init:
    build: .
    container_name: init
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        python manage.py migrate
    environment:
      ENGINE : django.db.backends.postgresql_psycopg2
      DB_NAME : cv_creation
      DB_USER : postgres
      DB_PASSWORD : Welcome411
      DB_HOST : pgsql
      DB_PORT : 5432
    depends_on:
      - pgsql 


 # Django Continer
  web:
    build: .
#    container_name: web_app
    depends_on:
      - init
    ports:
      - "8000-8999:8000"
    environment:
      ENGINE : django.db.backends.postgresql_psycopg2
      DB_NAME : cv_creation
      DB_USER : postgres
      DB_PASSWORD : Welcome411
      DB_HOST : pgsql
      DB_PORT : 5432
      
      
      
      