version: '3'

services:
  #PostgresDB
  pgsql:
    image: postgres:14
    container_name: pgsql
    # volumes: # Todo:// Add your volumes
    #   - /my/own/datadir:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB : ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"

  init:
    build: .
    container_name: init
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        python manage.py migrate
    env_file:
      - .env
    depends_on:
      - pgsql 


 # Django Continer
  web:
    build: .
#    container_name: web_app
    depends_on:
      - init
    ports:
      - "8000-8999:8000"
    env_file:
      - .env