apiVersion: v1
kind: Service
metadata:
  labels:
    app: cv-creation-svc
  name: cv-creation-svc
spec:
  type: NodePort
  selector:
    app: cv-creation  #Todo: add the lable of deployment app
  ports:
  - name: targetport
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31480